
name: PHPUnit
on:
  push:
    branches:
      - 4.x
      - github-workflows

env:
  PKG_NAME: trpgeno
  MODULES: "trpgeno_genetics trpgeno_genotypes trpgeno_genomatrix trpgeno_qtl trpgeno_vcf"
  PHPVER: "8.1"
  PGSQLVER: "13"
  DRUPALVER: "9.3.x-dev"
  IMAGE_TAG: "drupal9.3.x-dev-php8.1-pgsql13"
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Check out the repo
      - name: Checkout Repository
        uses: actions/checkout@v2
      # Here we pull the development tripaldocker image for this combo
      - name: Pull TripalDocker Image
        run: |
          docker pull tripalproject/tripaldocker:$IMAGE_TAG
      # Just spin up docker the good ol' fashion way
      # mounting our currently checked out package inside the docker container.
      - name: Spin up Docker locally
        run: |
          docker run --publish=80:80 --name=tripaldocker -tid \
            --volume=`pwd`:/var/www/drupal9/web/modules/$PKG_NAME tripalproject/tripaldocker:$IMAGE_TAG
      # Install the modules
      - name: Install our package in Docker
        run: |
          docker exec tripaldocker service postgresql restart
          docker exec tripaldocker drush en $MODULES --yes
      # Runs the PHPUnit tests.
      - name: Run PHPUnit Tests
        env:
          SIMPLETEST_BASE_URL: "http://localhost"
          SIMPLETEST_DB: "pgsql://drupaladmin:drupal9developmentonlylocal@localhost/sitedb"
          BROWSER_OUTPUT_DIRECTORY: "/var/www/drupal9/web/sites/default/files/simpletest"
        run: |
          docker exec tripaldocker service postgresql restart
          docker exec -e SIMPLETEST_BASE_URL=$SIMPLETEST_BASE_URL \
            -e SIMPLETEST_DB=$SIMPLETEST_DB \
            -e BROWSER_OUTPUT_DIRECTORY=$BROWSER_OUTPUT_DIRECTORY \
            --workdir=/var/www/drupal9/web/modules/$PKG_NAME \
            tripaldocker phpunit
